// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1HyZwH4vuY945QQzStnQDHhNW9uL5WOE',
    appId: '1:803675195198:web:6071e8b821096e50ce4e6f',
    messagingSenderId: '803675195198',
    projectId: 'absherk-e89ba',
    authDomain: 'absherk-e89ba.firebaseapp.com',
    storageBucket: 'absherk-e89ba.firebasestorage.app',
    measurementId: 'G-H9DE7XSDXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsYh6MKhrmDBy4VA9wC_3ri6XGeksjRP4',
    appId: '1:803675195198:android:6453848139369bc9ce4e6f',
    messagingSenderId: '803675195198',
    projectId: 'absherk-e89ba',
    storageBucket: 'absherk-e89ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyLIU0VLcA-tkyJnVlpSAUMZCS0GixyVg',
    appId: '1:803675195198:ios:6cc197c1405f2f0dce4e6f',
    messagingSenderId: '803675195198',
    projectId: 'absherk-e89ba',
    storageBucket: 'absherk-e89ba.firebasestorage.app',
    androidClientId: '803675195198-onllo3v2e77l9sql63gkbk5r97nf0bkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.absherk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyLIU0VLcA-tkyJnVlpSAUMZCS0GixyVg',
    appId: '1:803675195198:ios:6cc197c1405f2f0dce4e6f',
    messagingSenderId: '803675195198',
    projectId: 'absherk-e89ba',
    storageBucket: 'absherk-e89ba.firebasestorage.app',
    androidClientId: '803675195198-onllo3v2e77l9sql63gkbk5r97nf0bkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.absherk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1HyZwH4vuY945QQzStnQDHhNW9uL5WOE',
    appId: '1:803675195198:web:c47eb5ec6a3dfd6fce4e6f',
    messagingSenderId: '803675195198',
    projectId: 'absherk-e89ba',
    authDomain: 'absherk-e89ba.firebaseapp.com',
    storageBucket: 'absherk-e89ba.firebasestorage.app',
    measurementId: 'G-C1Q7YTE99M',
  );
}
